<?php
$sugar_config = array (
  'GOOGLE' => 
  array (
    'SCOPES' => 
    array (
      0 => 'https://www.googleapis.com/auth/drive',
      1 => 'https://www.googleapis.com/auth/calendar',
      2 => 'https://www.google.com/m8/feeds/',
      3 => 'https://www.googleapis.com/auth/drive',
      4 => 'https://www.googleapis.com/auth/drive',
      5 => 'https://www.googleapis.com/auth/drive',
      6 => 'https://www.googleapis.com/auth/drive',
      7 => 'https://www.googleapis.com/auth/drive',
      8 => 'https://www.googleapis.com/auth/drive',
      9 => 'https://www.googleapis.com/auth/drive',
      10 => 'https://www.googleapis.com/auth/drive',
      11 => 'https://www.googleapis.com/auth/drive',
      12 => 'https://www.googleapis.com/auth/drive',
      13 => 'https://www.googleapis.com/auth/drive',
      14 => 'https://www.googleapis.com/auth/drive',
      15 => 'https://www.googleapis.com/auth/drive',
      16 => 'https://www.googleapis.com/auth/drive',
      17 => 'https://www.googleapis.com/auth/drive',
      18 => 'https://www.googleapis.com/auth/drive',
      19 => 'https://www.googleapis.com/auth/drive',
      20 => 'https://www.googleapis.com/auth/drive',
      21 => 'https://www.googleapis.com/auth/drive',
      22 => 'https://www.googleapis.com/auth/drive',
      23 => 'https://www.googleapis.com/auth/drive',
      24 => 'https://www.googleapis.com/auth/drive',
      25 => 'https://www.googleapis.com/auth/drive',
      26 => 'https://www.googleapis.com/auth/drive',
      27 => 'https://www.googleapis.com/auth/drive',
      28 => 'https://www.googleapis.com/auth/drive',
      29 => 'https://www.googleapis.com/auth/drive',
      30 => 'https://www.googleapis.com/auth/drive',
      31 => 'https://www.googleapis.com/auth/drive',
      32 => 'https://www.googleapis.com/auth/drive',
      33 => 'https://www.googleapis.com/auth/drive',
      34 => 'https://www.googleapis.com/auth/drive',
      35 => 'https://www.googleapis.com/auth/drive',
      36 => 'https://www.googleapis.com/auth/drive',
      37 => 'https://www.googleapis.com/auth/drive',
      38 => 'https://www.googleapis.com/auth/drive',
      39 => 'https://www.googleapis.com/auth/drive',
      40 => 'https://www.googleapis.com/auth/drive',
      41 => 'https://www.googleapis.com/auth/drive',
      42 => 'https://www.googleapis.com/auth/drive',
      43 => 'https://www.googleapis.com/auth/drive',
      44 => 'https://www.googleapis.com/auth/drive',
      45 => 'https://www.googleapis.com/auth/drive',
      46 => 'https://www.googleapis.com/auth/drive',
      47 => 'https://www.googleapis.com/auth/drive',
      48 => 'https://www.googleapis.com/auth/drive',
      49 => 'https://www.googleapis.com/auth/drive',
      50 => 'https://www.googleapis.com/auth/drive',
      51 => 'https://www.googleapis.com/auth/drive',
      52 => 'https://www.googleapis.com/auth/drive',
      53 => 'https://www.googleapis.com/auth/drive',
      54 => 'https://www.googleapis.com/auth/drive',
      55 => 'https://www.googleapis.com/auth/drive',
      56 => 'https://www.googleapis.com/auth/drive',
      57 => 'https://www.googleapis.com/auth/drive',
      58 => 'https://www.googleapis.com/auth/drive',
      59 => 'https://www.googleapis.com/auth/drive',
      60 => 'https://www.googleapis.com/auth/drive',
      61 => 'https://www.googleapis.com/auth/drive',
    ),
    'APP_NAME' => 'RT GSync',
    'PROJECT_ID' => 'sincere-office-185506',
    'CLIENT_ID' => '764812510524-8bcbajv8ibve4lhd7sealuvg50l2qqi9.apps.googleusercontent.com',
    'CLIENT_SECRET' => 'hV_3dKkt6_OZbwCzwOpa4scl',
    'STATE' => '',
    'REDIRECT_URI' => 'https://cdn-plugins.rolustech.com/gsync/redirect.php',
    'APP_ID' => 'AIzaSyAKaAyz0rPj722dpy0qkgY_6vcc1U2EjnQ',
  ),
  'SAML_SLO' => '',
  'SAML_X509Cert' => '',
  'SAML_idp_entityId' => '',
  'SAML_issuer' => '',
  'SAML_loginurl' => '',
  'SAML_provisionUser' => 'on',
  'SAML_request_signing_method' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
  'activity_streams' => 
  array (
    'erasure_job_limit' => 5,
    'erasure_job_delay' => 0,
  ),
  'activity_streams_enabled' => true,
  'addAjaxBannedModules' => 
  array (
    0 => 'rt_GSync',
    1 => 'rt_GSync',
    2 => 'rt_GSync',
    3 => 'rt_GSync',
    4 => 'rt_GSync',
    5 => 'rt_GSync',
    6 => 'rt_GSync',
    7 => 'rt_GSync',
    8 => 'rt_GSync',
    9 => 'rt_GSync',
    10 => 'rt_GSync',
    11 => 'rt_GSync',
    12 => 'rt_GSync',
    13 => 'rt_GSync',
    14 => 'rt_GSync',
    15 => 'rt_GSync',
    16 => 'rt_GSync',
    17 => 'rt_GSync',
    18 => 'rt_GSync',
    19 => 'rt_GSync',
    20 => 'rt_GSync',
    21 => 'rt_GSync',
    22 => 'rt_GSync',
    23 => 'rt_GSync',
    24 => 'rt_GSync',
    25 => 'rt_GSync',
    26 => 'rt_GSync',
    27 => 'rt_GSync',
    28 => 'rt_GSync',
    29 => 'rt_GSync',
    30 => 'rt_GSync',
    31 => 'rt_GSync',
    32 => 'rt_GSync',
    33 => 'rt_GSync',
    34 => 'rt_GSync',
    35 => 'rt_GSync',
    36 => 'rt_GSync',
    37 => 'rt_GSync',
    38 => 'rt_GSync',
    39 => 'rt_GSync',
    40 => 'rt_GSync',
    41 => 'rt_GSync',
    42 => 'rt_GSync',
    43 => 'rt_GSync',
    44 => 'rt_GSync',
    45 => 'rt_GSync',
    46 => 'rt_GSync',
    47 => 'rt_GSync',
    48 => 'rt_GSync',
    49 => 'rt_GSync',
    50 => 'rt_GSync',
    51 => 'rt_GSync',
    52 => 'rt_GSync',
    53 => 'rt_GSync',
    54 => 'rt_GSync',
    55 => 'rt_GSync',
    56 => 'rt_GSync',
    57 => 'rt_GSync',
    58 => 'rt_GSync',
    59 => 'rt_GSync',
    60 => 'rt_GSync',
    61 => 'rt_GSync',
  ),
  'additional_js_config' => 
  array (
    'customer_journey' => 
    array (
      'enabled_modules' => 'Contacts,Accounts,Opportunities,Cases,Leads,m_CAMS',
    ),
  ),
  'admin_access_control' => false,
  'admin_export_only' => false,
  'allow_sendmail_outbound' => false,
  'analytics' => 
  array (
    'enabled' => true,
    'connector' => 'GoogleAnalytics',
    'id' => 'UA-46213331-3',
  ),
  'cache_dir' => 'cache/',
  'calculate_response_time' => true,
  'calendar' => 
  array (
    'default_view' => 'week',
    'show_calls_by_default' => true,
    'show_tasks_by_default' => true,
    'editview_width' => 990,
    'editview_height' => 465,
    'day_timestep' => 15,
    'week_timestep' => 30,
    'items_draggable' => true,
    'items_resizable' => true,
    'enable_repeat' => true,
    'max_repeat_count' => 1000,
  ),
  'calender_sync_lock' => false,
  'chartEngine' => 'sucrose',
  'collapse_subpanels' => false,
  'common_ml_dir' => '',
  'create_default_user' => false,
  'cron' => 
  array (
    'max_cron_jobs' => 25,
    'max_cron_runtime' => 1800,
    'min_cron_interval' => 30,
    'enforce_runtime' => false,
  ),
  'csrf' => 
  array (
    'soft_fail_form' => true,
  ),
  'currency' => '-99',
  'dashlet_display_row_options' => 
  array (
    0 => '1',
    1 => '3',
    2 => '5',
    3 => '10',
  ),
  'date_formats' => 
  array (
    'Y-m-d' => '2010-12-23',
    'm-d-Y' => '12-23-2010',
    'd-m-Y' => '23-12-2010',
    'Y/m/d' => '2010/12/23',
    'm/d/Y' => '12/23/2010',
    'd/m/Y' => '23/12/2010',
    'Y.m.d' => '2010.12.23',
    'd.m.Y' => '23.12.2010',
    'm.d.Y' => '12.23.2010',
  ),
  'datef' => 'm/d/Y',
  'db_manager' => 'MysqliManager',
  'dbconfig' => 
  array (
    'db_host_instance' => 'SQLEXPRESS',
    'db_type' => 'mysql',
    'db_port' => '',
    'db_manager' => 'MysqliManager',
    'db_host_name' => '192.168.3.44',
    'db_user_name' => 'karamatali',
    'db_password' => 'karamatali',
    'db_name' => 'karamatali_lukes8',
  ),
  'dbconfigoption' => 
  array (
    'persistent' => false,
    'autofree' => false,
    'debug' => 0,
    'ssl' => false,
    'collation' => 'utf8mb4_general_ci',
  ),
  'default_action' => 'index',
  'default_charset' => 'UTF-8',
  'default_currencies' => 
  array (
    'AUD' => 
    array (
      'name' => 'Australian Dollars',
      'iso4217' => 'AUD',
      'symbol' => '$',
    ),
    'BRL' => 
    array (
      'name' => 'Brazilian Reais',
      'iso4217' => 'BRL',
      'symbol' => 'R$',
    ),
    'GBP' => 
    array (
      'name' => 'British Pounds',
      'iso4217' => 'GBP',
      'symbol' => '£',
    ),
    'CAD' => 
    array (
      'name' => 'Canadian Dollars',
      'iso4217' => 'CAD',
      'symbol' => '$',
    ),
    'CNY' => 
    array (
      'name' => 'Chinese Yuan',
      'iso4217' => 'CNY',
      'symbol' => '￥',
    ),
    'EUR' => 
    array (
      'name' => 'Euro',
      'iso4217' => 'EUR',
      'symbol' => '€',
    ),
    'HKD' => 
    array (
      'name' => 'Hong Kong Dollars',
      'iso4217' => 'HKD',
      'symbol' => '$',
    ),
    'INR' => 
    array (
      'name' => 'Indian Rupees',
      'iso4217' => 'INR',
      'symbol' => '₨',
    ),
    'KRW' => 
    array (
      'name' => 'Korean Won',
      'iso4217' => 'KRW',
      'symbol' => '₩',
    ),
    'YEN' => 
    array (
      'name' => 'Japanese Yen',
      'iso4217' => 'JPY',
      'symbol' => '¥',
    ),
    'MXM' => 
    array (
      'name' => 'Mexican Pesos',
      'iso4217' => 'MXM',
      'symbol' => '$',
    ),
    'SGD' => 
    array (
      'name' => 'Singaporean Dollars',
      'iso4217' => 'SGD',
      'symbol' => '$',
    ),
    'CHF' => 
    array (
      'name' => 'Swiss Franc',
      'iso4217' => 'CHF',
      'symbol' => 'SFr.',
    ),
    'THB' => 
    array (
      'name' => 'Thai Baht',
      'iso4217' => 'THB',
      'symbol' => '฿',
    ),
    'USD' => 
    array (
      'name' => 'US Dollars',
      'iso4217' => 'USD',
      'symbol' => '$',
    ),
  ),
  'default_currency_iso4217' => 'USD',
  'default_currency_name' => 'US Dollar',
  'default_currency_show_preferred' => false,
  'default_currency_significant_digits' => '2',
  'default_currency_symbol' => '$',
  'default_date_format' => 'm/d/Y',
  'default_decimal_seperator' => '.',
  'default_email_charset' => 'UTF-8',
  'default_email_client' => 'sugar',
  'default_email_editor' => 'html',
  'default_export_charset' => 'UTF-8',
  'default_language' => 'en_us',
  'default_locale_name_format' => 's f l',
  'default_max_tabs' => '7',
  'default_module' => 'Home',
  'default_module_favicon' => false,
  'default_navigation_paradigm' => 'gm',
  'default_number_grouping_seperator' => ',',
  'default_password' => '',
  'default_permissions' => 
  array (
    'dir_mode' => 1528,
    'file_mode' => 432,
    'user' => '',
    'group' => '',
  ),
  'default_subpanel_links' => false,
  'default_subpanel_tabs' => false,
  'default_swap_last_viewed' => false,
  'default_swap_shortcuts' => false,
  'default_theme' => 'RacerX',
  'default_time_format' => 'h:i A',
  'default_user_is_admin' => false,
  'default_user_name' => '',
  'demoData' => 'no',
  'developerMode' => false,
  'diagnostic_file_max_lifetime' => 604800,
  'disable_convert_lead' => false,
  'disable_count_query' => true,
  'disable_export' => false,
  'disable_persistent_connections' => 'false',
  'disable_unknown_platforms' => false,
  'disable_user_email_config' => false,
  'disable_uw_upload' => true,
  'display_email_template_variable_chooser' => false,
  'display_inbound_email_buttons' => false,
  'dump_slow_queries' => false,
  'email_address_separator' => ',',
  'email_default_client' => 'sugar',
  'email_default_delete_attachments' => true,
  'email_default_editor' => 'html',
  'email_mailer_timeout' => 10,
  'email_xss' => 'YToxMzp7czo2OiJhcHBsZXQiO3M6NjoiYXBwbGV0IjtzOjQ6ImJhc2UiO3M6NDoiYmFzZSI7czo1OiJlbWJlZCI7czo1OiJlbWJlZCI7czo0OiJmb3JtIjtzOjQ6ImZvcm0iO3M6NToiZnJhbWUiO3M6NToiZnJhbWUiO3M6ODoiZnJhbWVzZXQiO3M6ODoiZnJhbWVzZXQiO3M6NjoiaWZyYW1lIjtzOjY6ImlmcmFtZSI7czo2OiJpbXBvcnQiO3M6ODoiXD9pbXBvcnQiO3M6NToibGF5ZXIiO3M6NToibGF5ZXIiO3M6NDoibGluayI7czo0OiJsaW5rIjtzOjY6Im9iamVjdCI7czo2OiJvYmplY3QiO3M6MzoieG1wIjtzOjM6InhtcCI7czo2OiJzY3JpcHQiO3M6Njoic2NyaXB0Ijt9',
  'enable_action_menu' => true,
  'enable_mobile_redirect' => true,
  'export_delimiter' => ',',
  'export_excel_compatible' => false,
  'external_cache_disabled' => true,
  'external_cache_disabled_apc' => true,
  'external_cache_disabled_db' => true,
  'external_cache_disabled_memcache' => true,
  'external_cache_disabled_memcached' => true,
  'external_cache_disabled_mongo' => true,
  'external_cache_disabled_smash' => true,
  'external_cache_disabled_wincache' => true,
  'external_cache_disabled_zend' => true,
  'full_text_engine' => 
  array (
    'Elastic' => 
    array (
      'valid' => true,
      'host' => 'localhost',
      'port' => 9200,
      'curl' => 
      array (
        10005 => '4a066e7a6de0b44c597cc0a341437197:CqX28BQrxabF2w==',
      ),
    ),
  ),
  'hide_admin_backup' => true,
  'hide_admin_licensing' => false,
  'hide_full_text_engine_config' => true,
  'hide_history_contacts_emails' => 
  array (
    'Cases' => true,
    'Accounts' => false,
    'Opportunities' => true,
  ),
  'history_max_viewed' => 50,
  'host_name' => 'localhost',
  'http_referer' => 
  array (
    'list' => 
    array (
      0 => 'dev.ms.sugarcrm.com',
      1 => 'stage.ms.sugarcrm.com',
      2 => 'qa.ms.sugarcrm.com',
      3 => 'prod.ms.sugarcrm.com',
      4 => 'vodafone.ms.sugarcrm.com',
      5 => 'apps.lotuslive.com',
      6 => 'www.sugarcrm.com',
    ),
    'actions' => 
    array (
      0 => 'index',
      1 => 'ListView',
      2 => 'DetailView',
      3 => 'EditView',
      4 => 'Login',
      5 => 'Authenticate',
      6 => 'oauth',
    ),
  ),
  'idm_mode' => 
  array (
    'enabled' => false,
  ),
  'import_max_execution_time' => 3600,
  'import_max_records_per_file' => 100,
  'import_max_records_total_limit' => '',
  'installer_locked' => true,
  'jobs' => 
  array (
    'min_retry_interval' => 30,
    'max_retries' => 5,
    'timeout' => 3600,
  ),
  'js_available' => 
  array (
    0 => 'emailTemplateForInvites',
    1 => 'emailTemplateForInvites',
  ),
  'js_custom_version' => 1,
  'js_lang_version' => 666,
  'languages' => 
  array (
    'en_us' => 'English (US)',
    'bg_BG' => 'Български',
    'cs_CZ' => 'Česky',
    'da_DK' => 'Dansk',
    'de_DE' => 'Deutsch',
    'el_EL' => 'Ελληνικά',
    'es_ES' => 'Español',
    'fr_FR' => 'Français',
    'he_IL' => 'עברית',
    'hu_HU' => 'Magyar',
    'hr_HR' => 'Hrvatski',
    'it_it' => 'Italiano',
    'lt_LT' => 'Lietuvių',
    'ja_JP' => '日本語',
    'ko_KR' => '한국어',
    'lv_LV' => 'Latviešu',
    'nb_NO' => 'Norsk',
    'nl_NL' => 'Nederlands',
    'pl_PL' => 'Polski',
    'pt_PT' => 'Português',
    'ro_RO' => 'Română',
    'ru_RU' => 'Русский',
    'sv_SE' => 'Svenska',
    'th_TH' => 'ไทย',
    'tr_TR' => 'Türkçe',
    'zh_TW' => '繁體中文',
    'zh_CN' => '简体中文',
    'pt_BR' => 'Português Brasileiro',
    'ca_ES' => 'Català',
    'en_UK' => 'English (UK)',
    'sr_RS' => 'Српски',
    'sk_SK' => 'Slovenčina',
    'sq_AL' => 'Shqip',
    'et_EE' => 'Eesti',
    'es_LA' => 'Español (Latinoamérica)',
    'fi_FI' => 'Suomi',
    'ar_SA' => 'العربية',
    'uk_UA' => 'Українська',
  ),
  'large_scale_test' => false,
  'lead_conv_activity_opt' => 'move',
  'list_max_entries_per_page' => '40',
  'list_max_entries_per_subpanel' => '15',
  'lock_default_user_name' => false,
  'lock_homepage' => false,
  'lock_subpanels' => false,
  'log_dir' => '.',
  'log_file' => 'sugarcrm.log',
  'log_memory_usage' => false,
  'logger' => 
  array (
    'level' => 'fatal',
    'file' => 
    array (
      'name' => 'sugarcrm',
      'suffix' => '',
      'ext' => '.log',
      'dateFormat' => '%c',
      'maxSize' => '10MB',
      'maxLogs' => 1,
    ),
    'channels' => 
    array (
      'input_validation' => 
      array (
        'level' => 'warning',
      ),
      'rest' => 
      array (
        'level' => 'warning',
      ),
    ),
  ),
  'logger_visible' => false,
  'marketing_extras_enabled' => true,
  'marketing_extras_url' => 'http://localhost/Luke_data/luke8',
  'mass_actions' => 
  array (
  ),
  'max_aggregate_email_attachments_bytes' => 10000000,
  'max_dashlets_homepage' => '15',
  'max_record_fetch_size' => 1000,
  'max_record_link_fetch_size' => 5000,
  'max_session_time' => '1',
  'merge_duplicates' => 
  array (
    'merge_relate_fetch_concurrency' => 2,
    'merge_relate_fetch_timeout' => 90000,
    'merge_relate_fetch_limit' => 20,
    'merge_relate_update_concurrency' => 4,
    'merge_relate_update_timeout' => 90000,
    'merge_relate_max_attempt' => 3,
  ),
  'metric_providers' => 
  array (
    'SugarMetric_Provider_Newrelic' => 'include/SugarMetric/Provider/Newrelic.php',
  ),
  'metric_settings' => 
  array (
    'SugarMetric_Provider_Newrelic' => 
    array (
      'applicationname' => 'SugarCRM 7.9.1.0',
    ),
  ),
  'metrics_enabled' => 1,
  'moduleInstaller' => 
  array (
    'packageScan' => true,
    'validExt' => 
    array (
      0 => 'eot',
      1 => 'svg',
      2 => 'tff',
      3 => 'woff',
      4 => 'woff2',
      5 => 'xml',
    ),
  ),
  'mothership' => 
  array (
    'fqdn' => 'prod.ms.sugarcrm.com',
  ),
  'name_formats' => 
  array (
    's f l' => 's f l',
    'f l' => 'f l',
    's l' => 's l',
    'l, s f' => 'l, s f',
    'l, f' => 'l, f',
    's l, f' => 's l, f',
    'l s f' => 'l s f',
    'l f s' => 'l f s',
  ),
  'new_email_addresses_opted_out' => false,
  'noPrivateTeamUpdate' => false,
  'oauth_token_expiry' => 0,
  'oauth_token_life' => 86400,
  'offlineEnabled' => true,
  'outfitters_licenses' => 
  array (
    'filter-deployer' => 'b6db142b5f74d32425f461ab493daf74',
    'gmail-sync' => '5b291574455452dbef0d73a19fa533a0',
  ),
  'packageScan' => true,
  'passwordsetting' => 
  array (
    'minpwdlength' => 6,
    'maxpwdlength' => '',
    'oneupper' => true,
    'onelower' => true,
    'onenumber' => true,
    'onespecial' => '0',
    'SystemGeneratedPasswordON' => '0',
    'generatepasswordtmpl' => 'acba4e94-764c-11e7-8479-02729de96d09',
    'lostpasswordtmpl' => 'acd39c32-764c-11e7-92ee-02729de96d09',
    'customregex' => '',
    'regexcomment' => '',
    'forgotpasswordON' => true,
    'linkexpiration' => true,
    'linkexpirationtime' => 24,
    'linkexpirationtype' => 60,
    'userexpiration' => '0',
    'userexpirationtime' => '',
    'userexpirationtype' => '1',
    'userexpirationlogin' => '',
    'systexpiration' => 1,
    'systexpirationtime' => 7,
    'systexpirationtype' => '0',
    'systexpirationlogin' => '',
    'lockoutexpiration' => '0',
    'lockoutexpirationtime' => '',
    'lockoutexpirationtype' => '1',
    'lockoutexpirationlogin' => '',
  ),
  'pdf_file_max_lifetime' => 86400,
  'pmse_settings_default' => 
  array (
    'logger_level' => 'critical',
    'error_number_of_cycles' => '10',
    'error_timeout' => '40',
  ),
  'portal_view' => 'single_user',
  'preview_edit' => true,
  'require_accounts' => false,
  'resource_management' => 
  array (
    'special_query_limit' => 50000,
    'special_query_modules' => 
    array (
      0 => 'Reports',
      1 => 'Export',
      2 => 'Import',
      3 => 'Administration',
      4 => 'Sync',
    ),
    'default_limit' => 1000,
  ),
  'roleBasedViews' => true,
  'rss_cache_time' => '10800',
  'save_query' => 'all',
  'search_engine' => 
  array (
    'max_bulk_threshold' => 25,
    'force_async_index' => true,
  ),
  'search_wildcard_char' => '%',
  'search_wildcard_infront' => false,
  'session_dir' => '',
  'showDetailData' => true,
  'showThemePicker' => true,
  'show_download_tab' => true,
  'site_url' => 'http://localhost/Luke_data/luke8',
  'slow_query_time_msec' => '5000',
  'smtp_mailer_debug' => 0,
  'snip_url' => 'https://ease.sugarcrm.com/',
  'stack_trace_errors' => false,
  'sugar_max_int' => 2147483647,
  'sugar_min_int' => -2147483648,
  'sugar_version' => '8.1.0',
  'team_based_acl' => 
  array (
    'enabled' => false,
    'enabled_modules' => 
    array (
    ),
  ),
  'time_formats' => 
  array (
    'H:i' => '23:00',
    'h:ia' => '11:00pm',
    'h:iA' => '11:00PM',
    'h:i a' => '11:00 pm',
    'h:i A' => '11:00 PM',
    'H.i' => '23.00',
    'h.ia' => '11.00pm',
    'h.iA' => '11.00PM',
    'h.i a' => '11.00 pm',
    'h.i A' => '11.00 PM',
  ),
  'timef' => 'H:i',
  'tmp_dir' => 'cache/xml/',
  'tmp_file_max_lifetime' => 86400,
  'tracker_max_display_length' => 30,
  'translation_string_prefix' => false,
  'unique_key' => '4a066e7a6de0b44c597cc0a341437197',
  'upload_badext' => 
  array (
    0 => 'php',
    1 => 'php3',
    2 => 'php4',
    3 => 'php5',
    4 => 'pl',
    5 => 'cgi',
    6 => 'py',
    7 => 'asp',
    8 => 'cfm',
    9 => 'js',
    10 => 'vbs',
    11 => 'html',
    12 => 'htm',
  ),
  'upload_dir' => 'upload/',
  'upload_maxsize' => '40554432 ',
  'use_common_ml_dir' => false,
  'use_real_names' => true,
  'use_sprites' => true,
  'vcal_time' => '2',
  'verify_client_ip' => true,
  'wl_list_max_entries_per_page' => 10,
  'wl_list_max_entries_per_subpanel' => 3,
);
