<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN mvh_Colorselection
 */


class mvh_Colorselection_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'mvh_Colorselection';
    public $object_name = 'mvh_Colorselection';
    public $table_name = 'mvh_colorselection';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $locked_fields;
    public $locked_fields_link;
    public $exterior_body_paint;
    public $exterior_body_paint_id;
    public $exterior_trim_paint;
    public $exterior_trim_paint_id;
    public $accent_front_door_paint;
    public $accent_front_door_paint_id;
    public $roof_color;
    public $vinyl_windows;
    public $masonry;
    public $tub_window;
    public $interior_wall_color;
    public $interior_wall_color_id;
    public $interior_trim_color;
    public $interior_trim_color_id;
    public $species;
    public $color;
    public $door_style;
    public $knobs_pulls;
    public $exterior_notes;
    public $interior_notes;
    public $cabinets_notes;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}